/**
 * generated by Xtext
 */
package org.sqlproc.dsl.generator;

import com.google.inject.Inject;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.sqlproc.dsl.ImportManager;
import org.sqlproc.dsl.processorDsl.EnumProperty;
import org.sqlproc.dsl.processorDsl.PojoEntity;
import org.sqlproc.dsl.processorDsl.PojoProperty;
import org.sqlproc.dsl.processorDsl.PojoType;
import org.sqlproc.dsl.util.Utils;

@SuppressWarnings("all")
public class ProcessorGeneratorUtils {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  public CharSequence compileType(final EnumProperty f, final ImportManager im) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\nType mismatch: cannot convert from PojoType to JvmType"
      + "\n!= cannot be resolved"
      + "\nsubstring cannot be resolved");
  }
  
  public CharSequence compileType(final PojoProperty f, final ImportManager im) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getRef is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getRef is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getGtype is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getGtype is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getGref is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getGref is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method array is undefined for the type ProcessorGeneratorUtils"
      + "\nType mismatch: cannot convert from PojoType to JvmType"
      + "\n!= cannot be resolved"
      + "\nsubstring cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved");
  }
  
  public CharSequence compileType(final PojoType f, final ImportManager im) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\nThe method getNative is undefined for the type ProcessorGeneratorUtils"
      + "\n!= cannot be resolved"
      + "\nsubstring cannot be resolved");
  }
  
  public String completeName(final PojoEntity e) {
    String _package = Utils.getPackage(e);
    String _plus = (_package + ".");
    String _name = e.getName();
    return (_plus + _name);
  }
}
