/*
* generated by Xtext
*/
package org.sqlproc.meta;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ProcessorMetaStandaloneSetup extends ProcessorMetaStandaloneSetupGenerated{

	public static void doSetup() {
		new ProcessorMetaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

