/*
* generated by Xtext
*/
package org.sqlproc.model;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ProcessorModelStandaloneSetup extends ProcessorModelStandaloneSetupGenerated{

	public static void doSetup() {
		new ProcessorModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

